sonar.verbose=true
sonar.organization=gurtulavinay01
sonar.projectKey=gurtulavinay01_New_project
sonar.projectName=New_project
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

